# Define the function values which is used to build out the tool tip
barvalues <- function(y){
    if (is.null(y)) return(NULL)
    labs <- barData[barData$id == y$id, ]
    tip <- paste( #
                "District : ", labs[, 2], "<br />",
                     "School : ", labs[, 3], "<br />",
                     "<table>",
                        "<tr>",
                            "<td>", " ", "</td>",
                            "<td>", "Grade : ", "</td>",
                            "<td>", labs[, 5], "</td>",
                            "<td>", "Total Points : ", "</td>",
                            "<td>", labs[, 6], "</td>",
                        "</tr>",
                        "<tr>",
                            "<td>"," ", "</td>",
                            "<td>", "Reading", "</td>",
                            "<td>", "Math", "</td>",
                            "<td>", "Science", "</td>",
                            "<td>", "US History", "</td>",
                        "</tr>",
                        "<tr>",
                            "<td>", "Proficiency", "</td>",
                            "<td>", labs[, 7], "</td>",
                            "<td>", labs[, 8], "</td>",
                            "<td>", labs[, 9], "</td>",
                            "<td>", labs[, 10], "</td>",
                        "</tr>",
                        "<tr>",
                            "<td>", "Growth All", "</td>",
                            "<td>", labs[, 11], "</td>",
                            "<td>", labs[, 12], "</td>",
                            "<td>", "Graduation Rate", "</td>",
                            "<td>", "Participation Rate", "</td>",
                        "</tr>",
                        "<tr>",
                            "<td>", "Growth Low 25%", "</td>",
                            "<td>", labs[, 13], "</td>",
                            "<td>", labs[, 14], "</td>",
                            "<td>", labs[, 15], "</td>",
                            "<td>", labs[, 16], "</td>",
                        "</tr>",
                    "</table>")
}
